### ISSUE TITLE
nothing info get from infohash.log but start note

### ISSUE THREAD

**Issue by jobsfan** [ylqjgm/DHT#2]
first of all, I am chinese, my english is not good, I don't know why two chinese people chat with english.

I follow your document, and cli the dht.php, a long long time, just get nothing in the infohash.log but the start note.

I use your write function in WorkerStart   Receive Timer etc. however nothing happen.

I guess our government sheild the port 6882 6881, can you pls tell me why I got nothing? should I run this on outboard VPS, maybe linode vps?

**Comment by ylqjgm** [comment]
你可以说中文....
